export enum ActionType {
    NO_RIGHTS = "NO_RIGHTS",
    OPEN_PROJECT = "OPEN_PROJECT",
    CURSOR_POSITION = "CURSOR_POSITION",

    ADD_PAGE = "ADD_PAGE",
    DELETE_PAGE = "DELETE_PAGE",
    RENAME_PAGE = "RENAME_PAGE",

    ADD_LAYER = "ADD_LAYER",
    DELETE_LAYER = "DELETE_LAYER",
    RENAME_LAYER = "RENAME_LAYER",
    CHANGE_LAYER_VISIBLE = "CHANGE_LAYER_VISIBLE",

    ADD_SHAPE = "ADD_SHAPE",
    DELETE_SHAPE = "DELETE_SHAPE",
    CHANGE_GRAPHICAL_PROPERTY = "CHANGE_GRAPHICAL_PROPERTY",
    CHANGE_OBJECT_PROPERTY = "CHANGE_OBJECT_PROPERTY",
}