export enum ActionType {
    OPEN_PROJECT = "OPEN_PROJECT",

    ADD_PAGE = "ADD_PAGE",
    REMOVE_PAGE = "REMOVE_PAGE",
    RENAME_PAGE = "RENAME_PAGE",

    ADD_LAYER = "ADD_LAYER",
    REMOVE_LAYER = "REMOVE_LAYER",
    RENAME_LAYER = "RENAME_LAYER",
    CHANGE_LAYER_VISIBLE = "CHANGE_LAYER_VISIBLE",

    ADD_SHAPE = "ADD_SHAPE",
    CHANGE_GRAPHICAL_PROPERTY = "CHANGE_GRAPHICAL_PROPERTY"
}