export enum ShapeType {
    CIRCLE = "aa",
    RECTANGLE = "ab",
    ELLIPS = "ac",
    LINE = "ad",
    // POINT = "POINT",
    POLYLINE = "af",

    BEGIN_END = "ba",
    OPERATION = "bb",
    PROCESS = "bc",
    DECISION = "bd",
    MODIFICATION = "be",
    REPEAT = "bf",
    INPUT_OUTPUT = "bd",
    // COMMENTARY = "COMMENTARY",
    // POINTER = "POINTER",
    // PAGE_POINTER = "POINTER",

    // COMPOSITE = "COMPOSITE",

    DOOR = "ca",
    WINDOW = "cb",
    WALL = "cc",
    ROOM = "cd",
    STAIR = "ce",
    STOVE = "cf",
    TOILET = "cg",
    SINK = "ch",
    SHOWER_CABIN = "ci",
    BATH = "cj",
}